### ISSUE TITLE
Querying entities

### ISSUE THREAD

**Issue by stzoran1** [AshkanAbd/efCoreSoftDeletes#1]
Thank you for this great extension. I checked it in detail and noticed there is no native way to "hide" soft deleted data when querying.

Do you have any suggestions how to achieve that?

**Comment by stzoran1** [comment]
I found interesting solution:

https://haacked.com/archive/2019/07/29/query-filter-by-interface/

**Comment by AshkanAbd** [comment]
Hi @stzoran1, thank you for your attention.
As I noted in scope 3.2 of [the proposal](https://1drv.ms/b/s!AirwjkMOI-BwkAzedA6E6YVkZqjQ?e=vfV2hq), you should use query filters in your application's context for querying soft deleted data.
Like this: `modelBuilder.Entity<Category>().HasQueryFilter(x => x.DeletedAt == null);`
In future versions, I will implement another way to querying soft-delete data.

**Comment by stzoran1** [comment]
Thank you for quick reply.
