### ISSUE TITLE
Losing foreign keys on soft delete

### ISSUE THREAD

**Issue by nonoodev** [AshkanAbd/efCoreSoftDeletes#10]
At first, thanks for this amazing feature.

I'm just facing a small issue.
If we have a class A that contains a class B that have a foreignkey to the class A, when we use the context.Remove() or context.RemoveAsync() on the class A, the class B become orphan (the id of the class A will be null) even if it's not a force delete.

Do you have a workaround?

Thank you

**Comment by AshkanAbd** [comment]
Hi, sorry for my late reply.   
`ForceDelete` method will fully delete `A`. Based on what you have configured in `DbContext`, `B` will be deleted or maybe set to `null`.     
`Remove` and `RemoveAsync` methods will call `LoadRelations` and `OnSoftDelete` methods in `A` class. You can soft-delete `B` or force delete it or set it to `null`.    
If you have more questions, feel free to ask.
