### ISSUE TITLE
Using LoadRelations and OnSoftDelete

### ISSUE THREAD

**Issue by stzoran1** [AshkanAbd/efCoreSoftDeletes#3]
Hi,

I am facing difficulties using LoadRelations and OnSoftDelete to soft delete related data. Can you please post some code examples for better overview and faster start?

Also, I am interested in donating some money for this project. Do you accept PayPal instead of bitcoin wallet?

**Comment by AshkanAbd** [comment]
Hi @stzoran1,
I recently add [a sample project](https://github.com/AshkanAbd/efCoreSoftDeletesSample) for it. please check models and DbContext in that project.   

Sorry but I don't have access to PayPal in my country, I can only accept BTC.

**Comment by stzoran1** [comment]
Thank you for quick reply and great examples. I will implement them in my project tomorrow ;)

I manged to send you some humble BitCoin donation.

**Comment by AshkanAbd** [comment]
Thank you.
