### ISSUE TITLE
CreatedAt value messed on update

### ISSUE THREAD

**Issue by stzoran1** [AshkanAbd/efCoreSoftDeletes#4]
I noticed one issue when using standard scaffolded controllers. They are using next method to update records:

`context.Entry(product).State = EntityState.Modified;`

In this case CreatedAt is set to: 0001-01-01 00:00:00.0000000

I expect CreatedAt not to be changed. It is set at moment of inserting and then it should be intact no matter what.

**Comment by stzoran1** [comment]
Some additional details... I just noticed when this approach is used all timestamps are reset to default value due to fact they are not included in post request and only UpdatedAt is then set properly due to fact we have EntityState.Modified. We need a way to handle this and prevent setting them to default values.

**Comment by stzoran1** [comment]
I come up with possible solution for this:

```
 protected virtual void SetModifiedEntitiesTimestamps()
        {
            var updatedRecords = ChangeTracker.Entries()
                .Where(x => x.State == EntityState.Modified && x.Entity is ITimestamps)
                .Select(x => x.Entity);
            foreach (var record in updatedRecords) {
                if (record == null) continue;
                this.Entry(record).Property("CreatedAt").IsModified = false;
                var r = (ITimestamps)record;
                if (r == null) continue;
                r.UpdatedAt = DateTime.Now;
            }
        }
```

This is quick solution I found working on my side. Maybe not most elegant :)

**Comment by stzoran1** [comment]
I wanted to push changes I made but I failed. I don't have sufficient rights. If you want you can add me as contributor and I will make pull request with my solution so you can decide do you want to accept it or not.

**Comment by stzoran1** [comment]
Here is my complete solution:

```
        protected virtual void SetModifiedEntitiesTimestamps()
        {
            var updatedRecords = ChangeTracker.Entries()
                .Where(x => x.State == EntityState.Modified && (x.Entity is ITimestamps || x.Entity is ISoftDelete))
                .Select(x => x.Entity);
            foreach (var record in updatedRecords) {
                if (record == null) continue;
                
                if(record is ISoftDelete)
                {
                    this.Entry(record).Property("DeletedAt").IsModified = false;
                }

                if (record is ITimestamps)
                {
                    
                    this.Entry(record).Property("CreatedAt").IsModified = false;

                    var r = (ITimestamps)record;
                    if (r == null) continue;
                    r.UpdatedAt = DateTime.Now;
                }
                
            }
        }
```

**Comment by AshkanAbd** [comment]
Hi @stzoran1, thank you for fixing the bug.
Please fork this repo, implement your solution and send a pull request to merge your change.

**Comment by stzoran1** [comment]
@AshkanAbd pull request created.
